/* Supabase가 연결되기 전에는 화면 검토를 위한 이 브라우저 전용 미리보기로 동작합니다. */
(() => {
  const config = window.POLITIMON_SUPABASE || {};
  const configured = /^https:\/\/.+\.supabase\.co$/i.test(config.url || "") && !!config.anonKey;
  const local = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)); } catch { return fallback; } };
  const put = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  const id = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
  let client = null;
  const clientReady = configured ? import("https://esm.sh/@supabase/supabase-js@2").then(({ createClient }) => client = createClient(config.url, config.anonKey)) : Promise.resolve(null);
  const localUserKey = "politimon-preview-user-v1";
  const previewUser = () => local(localUserKey, null);
  const usersRoom = room => ({ ...room, members: room.members || [] });
  const api = {
    configured,
    async getSession() { await clientReady; if (!client) return previewUser() ? { user: previewUser(), preview: true } : null; const { data } = await client.auth.getSession(); return data.session; },
    async getDeveloperProfile(userId) { await clientReady; if (!client || !userId) return { is_developer: false }; const { data, error } = await client.from("profiles").select("is_developer").eq("id", userId).maybeSingle(); if (error) throw error; return data || { is_developer: false }; },
    async signUp(email, password, displayName) { await clientReady; if (!client) { const user = { id: id(), email, user_metadata: { display_name: displayName || email.split("@")[0] } }; put(localUserKey, user); return { user, session: { user }, preview: true, needsEmailConfirmation: false }; } const { data, error } = await client.auth.signUp({ email, password, options: { data: { display_name: displayName } } }); if (error) throw error; return { user: data.user, session: data.session, needsEmailConfirmation: !data.session }; },
    async signIn(email, password) { await clientReady; if (!client) { const user = { id: id(), email, user_metadata: { display_name: email.split("@")[0] } }; put(localUserKey, user); return { user, preview: true }; } const { data, error } = await client.auth.signInWithPassword({ email, password }); if (error) throw error; return data.session; },
    async signOut() { await clientReady; if (!client) { localStorage.removeItem(localUserKey); return; } const { error } = await client.auth.signOut(); if (error) throw error; },
    async deleteAccount() { await clientReady; if (!client) { localStorage.removeItem(localUserKey); return; } const { error } = await client.functions.invoke("delete-account"); if (error) throw error; await client.auth.signOut({ scope:"local" }); },
    async listPosts() { await clientReady; if (!client) return local("politimon-preview-posts-v1", []).sort((a,b) => b.created_at.localeCompare(a.created_at)); const { data, error } = await client.from("gallery_posts").select("id,title,body,created_at,profiles(display_name)").order("created_at", { ascending:false }).limit(100); if (error) throw error; return data.map(post => ({ ...post, author: post.profiles?.display_name || "익명" })); },
    async createPost(title, body, user) { await clientReady; if (!client) { const posts = local("politimon-preview-posts-v1", []); const post = { id:id(), title, body, author:user.user_metadata?.display_name || user.email.split("@")[0], created_at:new Date().toISOString() }; posts.push(post); put("politimon-preview-posts-v1", posts); return post; } const { data, error } = await client.from("gallery_posts").insert({ title, body }).select("id,title,body,created_at,profiles(display_name)").single(); if (error) throw error; return { ...data, author:data.profiles?.display_name || "나" }; },
    async deletePost(postId) { await clientReady; if (!client) { const posts = local("politimon-preview-posts-v1", []); put("politimon-preview-posts-v1", posts.filter(post => post.id !== postId)); return; } const { error } = await client.rpc("delete_gallery_post", { p_post_id:postId }); if (error) throw error; },
    async listRooms() { await clientReady; if (!client) return local("politimon-preview-rooms-v1", []).filter(room => room.status === "waiting"); const { data, error } = await client.rpc("list_public_rooms"); if (error) throw error; return data; },
    async createRoom(input, user) { await clientReady; if (!client) { const rooms = local("politimon-preview-rooms-v1", []); const room = { id:id(), title:input.title, is_private:input.isPrivate, password:input.password || "", owner_id:user.id, owner_name:user.user_metadata?.display_name || user.email.split("@")[0], max_players:2, status:"waiting", members:[{ user_id:user.id, display_name:user.user_metadata?.display_name || user.email.split("@")[0], ready:true, is_host:true }] }; rooms.unshift(room); put("politimon-preview-rooms-v1", rooms); return room; } const { data, error } = await client.rpc("create_room", { p_title:input.title, p_is_private:input.isPrivate, p_password:input.password || null }); if (error) throw error; return data; },
    async joinRoom(roomId, password, user) { await clientReady; if (!client) { const rooms = local("politimon-preview-rooms-v1", []); const room = rooms.find(x => x.id === roomId); if (!room) throw new Error("방을 찾을 수 없습니다."); if (room.is_private && room.password !== password) throw new Error("비밀번호가 맞지 않습니다."); if (!room.members.some(x => x.user_id === user.id)) room.members.push({ user_id:user.id, display_name:user.user_metadata?.display_name || user.email.split("@")[0], ready:false, is_host:false }); put("politimon-preview-rooms-v1", rooms); return room; } const { data, error } = await client.rpc("join_room", { p_room_id:roomId, p_password:password || null }); if (error) throw error; return data; },
    async setReady(roomId, ready) { await clientReady; if (!client) { const user = previewUser(), rooms = local("politimon-preview-rooms-v1", []), room = rooms.find(x => x.id === roomId); const member = room?.members.find(x => x.user_id === user?.id); if (member) member.ready = ready; put("politimon-preview-rooms-v1", rooms); return room; } const { data, error } = await client.rpc("set_room_ready", { p_room_id:roomId, p_ready:ready }); if (error) throw error; return data; },
    async leaveRoom(roomId, user) { await clientReady; if (!client) { const rooms = local("politimon-preview-rooms-v1", []), room = rooms.find(x => x.id === roomId); if (!room) return { deleted:true }; room.members = room.members.filter(member => member.user_id !== user?.id); if (!room.members.length) { put("politimon-preview-rooms-v1", rooms.filter(item => item.id !== roomId)); return { deleted:true }; } if (room.owner_id === user?.id) { const nextHost = room.members[0]; room.owner_id = nextHost.user_id; room.members.forEach(member => { member.is_host = member.user_id === nextHost.user_id; }); } put("politimon-preview-rooms-v1", rooms); return { deleted:false }; } const { data, error } = await client.rpc("leave_room", { p_room_id:roomId }); if (error) throw error; return data; },
    async startRoom(roomId) { await clientReady; if (!client) { const rooms = local("politimon-preview-rooms-v1", []), room = rooms.find(x => x.id === roomId); if (!room || room.members.length !== 2 || !room.members.every(x => x.ready)) throw new Error("두 명 모두 준비해야 시작할 수 있습니다."); room.status = "playing"; put("politimon-preview-rooms-v1", rooms); return room; } const { data, error } = await client.rpc("start_room", { p_room_id:roomId }); if (error) throw error; return data; }
  };
  window.politimonBackend = api;
})();
