/* Supabase가 연결되기 전에는 화면 검토를 위한 이 브라우저 전용 미리보기로 동작합니다. */
(() => {
  const config = window.POLITIMON_SUPABASE || {};
  const configured = /^https:\/\/.+\.supabase\.co$/i.test(config.url || "") && !!config.anonKey;
  const local = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)); } catch { return fallback; } };
  const put = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  const id = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
  let client = null;
  const clientReady = configured ? import("https://esm.sh/@supabase/supabase-js@2").then(({ createClient }) => client = createClient(config.url, config.anonKey)) : Promise.resolve(null);
  const localUserKey = "politimon-preview-user-v1";
  const previewUsersKey = "politimon-preview-users-v1";
  const previewUser = () => local(localUserKey, null);
  const previewAccount = (email, displayName="") => {
    const normalizedEmail = String(email || "").trim().toLowerCase(), users = local(previewUsersKey, {}), current = previewUser();
    const existing = users[normalizedEmail] || (String(current?.email || "").toLowerCase() === normalizedEmail ? current : null);
    const user = existing || { id:id(), email:normalizedEmail, user_metadata:{ display_name:displayName || normalizedEmail.split("@")[0] } };
    if (displayName) user.user_metadata = { ...(user.user_metadata || {}), display_name:displayName };
    users[normalizedEmail] = user;
    put(previewUsersKey, users);
    return user;
  };
  const seoulDateKey = value => {
    const parts = Object.fromEntries(new Intl.DateTimeFormat("en-US", { timeZone:"Asia/Seoul", year:"numeric", month:"2-digit", day:"2-digit" }).formatToParts(new Date(value)).map(part=>[part.type,part.value]));
    return `${parts.year}-${parts.month}-${parts.day}`;
  };
  const usersRoom = room => ({ ...room, members: room.members || [] });
  const api = {
    configured,
    async getSession() { await clientReady; if (!client) return previewUser() ? { user: previewUser(), preview: true } : null; const { data } = await client.auth.getSession(); return data.session; },
    async getDeveloperProfile(userId) { await clientReady; if (!client || !userId) return { is_developer: false }; const { data, error } = await client.from("profiles").select("is_developer").eq("id", userId).maybeSingle(); if (error) throw error; return data || { is_developer: false }; },
    async getGameProfile(userId) { await clientReady; if (!userId) return null; if (!client) return local(`politimon-preview-game-profile-v1:${userId}`, null); const { data, error } = await client.rpc("get_game_profile"); if (error) throw error; return data || null; },
    async saveGameProfile(userId, profile, expectedRevision, seasonId) { await clientReady; if (!userId) throw new Error("로그인이 필요합니다."); if (!client) { const key=`politimon-preview-game-profile-v1:${userId}`,prior=local(key,null),revision=Number(prior?.revision||0)+1,result={profile,revision,seasonId,updatedAt:new Date().toISOString()};put(key,result);return result; } const { data, error } = await client.rpc("save_game_profile", { p_profile:profile, p_expected_revision:expectedRevision??null, p_season_id:seasonId }); if (error) throw error; return data; },
    async claimDailyLoginReward(userId, now=new Date()) { await clientReady; if (!userId) throw new Error("로그인이 필요합니다."); if (!client) { const profileKey=`politimon-preview-game-profile-v1:${userId}`,rewardKey=`politimon-preview-daily-login-v1:${userId}`,saved=local(profileKey,null);if(!saved)throw new Error("게임 프로필을 먼저 만들어야 합니다.");const date=seoulDateKey(now),last=local(rewardKey,null);if(last?.date===date)return{...saved,claimed:false,amount:0,date};const profile=JSON.parse(JSON.stringify(saved.profile||{}));profile.currency=Number(profile.currency||0)+50;const result={profile,revision:Number(saved.revision||0)+1,seasonId:saved.seasonId,updatedAt:new Date().toISOString(),claimed:true,amount:50,date};put(profileKey,{profile:result.profile,revision:result.revision,seasonId:result.seasonId,updatedAt:result.updatedAt});put(rewardKey,{date,amount:50});return result; } const { data, error } = await client.rpc("claim_daily_login_reward"); if (error) throw error; return data; },
    async signUp(email, password, displayName) { await clientReady; if (!client) { const user=previewAccount(email,displayName); put(localUserKey, user); return { user, session: { user }, preview: true, needsEmailConfirmation: false }; } const { data, error } = await client.auth.signUp({ email, password, options: { data: { display_name: displayName } } }); if (error) throw error; return { user: data.user, session: data.session, needsEmailConfirmation: !data.session }; },
    async signIn(email, password) { await clientReady; if (!client) { const user=previewAccount(email); put(localUserKey, user); return { user, preview: true }; } const { data, error } = await client.auth.signInWithPassword({ email, password }); if (error) throw error; return data.session; },
    async signOut() { await clientReady; if (!client) { localStorage.removeItem(localUserKey); return; } const { error } = await client.auth.signOut(); if (error) throw error; },
    async deleteAccount() { await clientReady; if (!client) { localStorage.removeItem(localUserKey); return; } const { error } = await client.functions.invoke("delete-account"); if (error) throw error; await client.auth.signOut({ scope:"local" }); },
    async listPosts() { await clientReady; if (!client) return local("politimon-preview-posts-v1", []).sort((a,b) => b.created_at.localeCompare(a.created_at)); const { data, error } = await client.from("gallery_posts").select("id,author_id,title,body,created_at,profiles(display_name)").order("created_at", { ascending:false }).limit(100); if (error) throw error; return data.map(post => ({ ...post, author: post.profiles?.display_name || "익명" })); },
    async createPost(title, body, user) { await clientReady; if (!client) { const post = { id:id(), author_id:user.id, title, body, author:user.user_metadata?.display_name || user.email.split("@")[0], created_at:new Date().toISOString() }, posts = local("politimon-preview-posts-v1", []); posts.push(post); put("politimon-preview-posts-v1", posts); return post; } const { data, error } = await client.from("gallery_posts").insert({ title, body }).select("id,author_id,title,body,created_at,profiles(display_name)").single(); if (error) throw error; return { ...data, author:data.profiles?.display_name || "나" }; },
    async deletePost(postId) { await clientReady; if (!client) { const posts = local("politimon-preview-posts-v1", []); put("politimon-preview-posts-v1", posts.filter(post => post.id !== postId)); return; } const { error } = await client.rpc("delete_gallery_post", { p_post_id:postId }); if (error) throw error; },
    async listRooms() { await clientReady; if (!client) return local("politimon-preview-rooms-v1", []).filter(room => room.status === "waiting"); const { data, error } = await client.rpc("list_public_rooms"); if (error) throw error; return data; },
    async createRoom(input, user) { await clientReady; if (!client) { const rooms = local("politimon-preview-rooms-v1", []); const room = { id:id(), title:input.title, is_private:input.isPrivate, password:input.password || "", owner_id:user.id, owner_name:user.user_metadata?.display_name || user.email.split("@")[0], max_players:2, status:"waiting", members:[{ user_id:user.id, display_name:user.user_metadata?.display_name || user.email.split("@")[0], ready:true, is_host:true }] }; rooms.unshift(room); put("politimon-preview-rooms-v1", rooms); return room; } const { data, error } = await client.rpc("create_room", { p_title:input.title, p_is_private:input.isPrivate, p_password:input.password || null }); if (error) throw error; return data; },
    async joinRoom(roomId, password, user) { await clientReady; if (!client) { const rooms = local("politimon-preview-rooms-v1", []); const room = rooms.find(x => x.id === roomId); if (!room) throw new Error("방을 찾을 수 없습니다."); if (room.is_private && room.password !== password) throw new Error("비밀번호가 맞지 않습니다."); if (!room.members.some(x => x.user_id === user.id)) room.members.push({ user_id:user.id, display_name:user.user_metadata?.display_name || user.email.split("@")[0], ready:false, is_host:false }); put("politimon-preview-rooms-v1", rooms); return room; } const { data, error } = await client.rpc("join_room", { p_room_id:roomId, p_password:password || null }); if (error) throw error; return data; },
    async getRoom(roomId) { await clientReady; if (!client) return local("politimon-preview-rooms-v1", []).find(room => room.id === roomId) || null; const { data, error } = await client.rpc("get_room", { p_room_id:roomId }); if (error) throw error; return data; },
    async setReady(roomId, ready) { await clientReady; if (!client) { const user = previewUser(), rooms = local("politimon-preview-rooms-v1", []), room = rooms.find(x => x.id === roomId); const member = room?.members.find(x => x.user_id === user?.id); if (member) member.ready = ready; put("politimon-preview-rooms-v1", rooms); return room; } const { data, error } = await client.rpc("set_room_ready", { p_room_id:roomId, p_ready:ready }); if (error) throw error; return data; },
    async leaveRoom(roomId, user) { await clientReady; if (!client) { const rooms = local("politimon-preview-rooms-v1", []), room = rooms.find(x => x.id === roomId); if (!room) return { deleted:true }; room.members = room.members.filter(member => member.user_id !== user?.id); if (!room.members.length) { put("politimon-preview-rooms-v1", rooms.filter(item => item.id !== roomId)); return { deleted:true }; } if (room.owner_id === user?.id) { const nextHost = room.members[0]; room.owner_id = nextHost.user_id; room.members.forEach(member => { member.is_host = member.user_id === nextHost.user_id; }); } put("politimon-preview-rooms-v1", rooms); return { deleted:false }; } const { data, error } = await client.rpc("leave_room", { p_room_id:roomId }); if (error) throw error; return data; },
    async setRoomDeck(roomId, deck) { await clientReady; if (!client) return; const { data, error } = await client.rpc("set_room_deck", { p_room_id:roomId, p_deck:deck }); if (error) throw error; return data; },
    async startRoom(roomId) { await clientReady; if (!client) throw new Error("실시간 PvP는 Supabase 연결 후 사용할 수 있습니다."); const { data, error } = await client.rpc("start_room", { p_room_id:roomId }); if (error) throw error; return data; },
    async startMatch(roomId, state, turnUserId) { await clientReady; if (!client) throw new Error("실시간 PvP는 Supabase 연결 후 사용할 수 있습니다."); const { data, error } = await client.rpc("start_match", { p_room_id:roomId, p_state:state, p_turn_user_id:turnUserId }); if (error) throw error; return data; },
    async getMatch(roomId) { await clientReady; if (!client) return null; const { data, error } = await client.rpc("get_match", { p_room_id:roomId }); if (error) throw error; return data; },
    async submitMatchState(matchId, version, state, nextTurnUserId, action) { await clientReady; if (!client) throw new Error("실시간 PvP는 Supabase 연결 후 사용할 수 있습니다."); const { data, error } = await client.rpc("submit_match_state", { p_match_id:matchId, p_expected_version:version, p_state:state, p_next_turn_user_id:nextTurnUserId, p_action:action }); if (error) throw error; return data; },
    async forfeitMatch(matchId, version) { await clientReady; if (!client) throw new Error("실시간 PvP는 Supabase 연결 후 사용할 수 있습니다."); const { data, error } = await client.rpc("forfeit_match", { p_match_id:matchId, p_expected_version:version }); if (error) throw error; return data; },
    subscribeMatch(roomId, onMatch, onError=()=>{}) {
      let channel=null, stopped=false;
      const refresh=async()=>{ try { const match=await api.getMatch(roomId); if (!stopped && match?.state && Object.keys(match.state).length) onMatch(match); } catch(error) { if(!stopped) onError(error); } };
      clientReady.then(()=>{ if(!client || stopped) return; channel=client.channel(`politimon-match-${roomId}`).on("postgres_changes",{event:"*",schema:"public",table:"matches",filter:`room_id=eq.${roomId}`},refresh).subscribe(status=>{ if(status==="SUBSCRIBED") refresh(); }); }).catch(onError);
      return ()=>{ stopped=true; if(channel && client) client.removeChannel(channel); };
    }
  };
  window.politimonBackend = api;
})();
