// 카드 추가: 이 파일의 cards에 데이터, assets/cards/{id}.png에 이미지를 추가하고 pack.cardIds에 ID를 등록합니다.
// 조건부 피해 설명은 "추가 피해 n" 형식으로 작성합니다.
// 색상 인식 기준: 현재 카드 이미지에서 갈색처럼 보이는 붉은/벽돌색 계열은 orange(주황)로 입력합니다.
// brown(갈색)은 이후 추가될 금색에 가까운 갈색 계열에만 사용합니다.
// 북한 인물은 tags에 "north_korea"를 붙이면 문재앙 VMAX의 내친구김정은 피해 계산에서 제외됩니다.
const RARITIES = ["HR", "SSR", "SR", "RR", "R", "U", "C"];

const settings = {
  initialHandSize: 4,
  deckCardCount: 10,
  characterLimit: 7,
  strategyLimit: 3,
  vmaxLimit: 1,
  ssrLimit: 2,
  packPrice: 100,                      // 팩별 가격이 없을 때 사용하는 기본값
  cardsPerPack: 5,
  rarityOdds: { HR: 0.8, SSR: 4.2, SR: 10, RR: 15, R: 20, U: 22, C: 28 },
  handRefillCount: 1,
  handRefillMethod: null,
  types: [
    { id: "white", label: "하양", color: "#ece8dc" },
    { id: "black", label: "검정", color: "#183352" },
    { id: "orange", label: "주황", color: "#ff8a00" },
    { id: "red", label: "빨강", color: "#ff1744" },
    { id: "green", label: "초록", color: "#1d932a" },
    { id: "yellow", label: "노랑", color: "#f7df0d" },
    { id: "gray", label: "회색", color: "#899098" },
    { id: "purple", label: "보라", color: "#7c3b8f" },
    { id: "blue", label: "파랑", color: "#0778cc" },
    { id: "pink", label: "분홍", color: "#ff4fd8" },
    { id: "brown", label: "갈색", color: "#a6891e" },
  ],
  retreatFallback: null,
  reward: { aiWin:60, aiLoss:15, pvpWin:90, pvpLoss:25 },
};

const cards = [
  { id:"character_01", name:"이재명", type:"character", stage:"v", rarity:"SSR", attribute:"pink", hp:250, weakness:"orange", resistance:"purple", retreatCost:{any:3}, tags:["criminal_record"],
    skills:[{name:"찢", cost:{pink:2}, description:"상대방을 찢어버린다. 40 피해", effects:[{type:"damage",amount:40}]},{name:"드럼통", cost:{pink:2, any:1}, description:"상대 인물의 현재 체력이 100 이하이면 즉시 제거합니다. 그렇지 않으면 80 피해", effects:[{type:"defeatIfHpAtOrBelow",threshold:100},{type:"damage",amount:80}]}] },
  { id:"character_02", name:"윤석열", type:"character", rarity:"SSR", attribute:"red", hp:240, weakness:"brown", resistance:"yellow", retreatCost:{any:3},
    trait:{name:"거부권", description:"20 피해. 상대 인물의 속성이 파란색이라면 +30", effects:[{type:"bonusDamageIfEnemyAttribute",attribute:"blue",amount:30},{type:"damage",amount:20}]},
    skills:[{name:"비상 계엄 선포", cost:{red:3, any:1}, description:"동전 던지기를 선택할 수 있다. 선택하면 앞면일 때 피해량 2배, 뒷면일 때 추가 피해 -50. 기본 110 피해", effects:[{type:"coinFlipDamageModifier",optional:true,headsMultiplier:2,tailsBonus:-50},{type:"damage",amount:110}]}] },
  { id:"character_03", name:"문재인", type:"character", stage:"v", rarity:"SSR", attribute:"blue", hp:240, weakness:"pink", resistance:"green", retreatCost:{any:3}, tags:["criminal_record"],
    skills:[{name:"갈라치기", cost:{blue:2}, description:"상대 필드에 여성 인물 카드가 있다면 +10. 기본 50 피해", effects:[{type:"bonusDamageIfEnemyTag",tag:"female",amount:10},{type:"damage",amount:50}]},{name:"미안하다 고맙다", cost:{blue:2, any:1}, description:"80 피해. 이 공격으로 상대 인물이 죽고 체력이 0 아래로 내려가면, 다음에 배치된 인물에게 초과 피해를 입힙니다.", effects:[{type:"damage",amount:80,overflowToReplacement:true}]}] },
  // trait 필드는 선택 사항입니다. 아래처럼 생략하면 게임에서 "특성 없음"으로 표시됩니다.
  { id:"character_04", name:"박근혜", type:"character", rarity:"RR", attribute:"red", hp:190, weakness:"blue", resistance:"yellow", retreatCost:{any:3}, tags:["female","criminal_record"],
    trait:{name:"박정희의 딸", description:"10 피해. 상대 인물 카드 속성이 빨간색이 아닌 경우 추가 피해 20", effects:[{type:"bonusDamageUnlessEnemyAttribute",attribute:"red",amount:20},{type:"damage",amount:10}]},
    skills:[{name:"사드 배치", cost:{red:2}, description:"현재 박근혜의 체력이 100 이상일 경우 추가 피해 20. 기본 50 피해", effects:[{type:"bonusDamageIfSelfHpAtLeast",threshold:100,amount:20},{type:"damage",amount:50}]}] },
  { id:"strategy_01", name:"선동", type:"strategy", rarity:"U", description:"상대에게서 원하는 토큰 1개를 빼앗아옵니다.", effects:[{type:"stealToken",amount:1}] },
  { id:"strategy_02", name:"녹취록", type:"strategy", rarity:"R", description:"상대 핸드에 있는 카드 1장을 무작위로 보고 다시 돌려줍니다.", effects:[{type:"revealRandomHand",amount:1}] },
  { id:"strategy_03", name:"감옥", type:"strategy", rarity:"R", description:"바로 다음 상대의 차례 때 기술을 사용할 수 없습니다. 전략 카드와 특성은 사용할 수 있습니다.", effects:[{type:"blockOpponentNextSkill"}] },
  { id:"strategy_04", name:"토론회", type:"strategy", rarity:"RR", description:"이번 턴 동전 던지기 1번을 앞면으로 던져졌다고 간주합니다.", effects:[{type:"forceNextCoinHeads"}] },
  { id:"character_05", name:"이명박", type:"character", rarity:"RR", attribute:"orange", hp:180, weakness:"blue", resistance:"red", retreatCost:{any:3}, packId:"pack_president", tags:["criminal_record"],
    skills:[{name:"물대포", cost:{blue:1}, description:"30 피해", effects:[{type:"damage",amount:30}]},{name:"다 거짓말인거 아시죠?", cost:{orange:3}, description:"동전이 앞면이면 추가 피해 20. 기본 70 피해", effects:[{type:"coinFlipDamageModifier",headsMultiplier:1,headsBonus:20,tailsBonus:0},{type:"damage",amount:70}]}] },
  { id:"character_06", name:"노무현", type:"character", rarity:"SSR", attribute:"blue", hp:250, weakness:"pink", resistance:"green", retreatCost:{any:3}, packId:"pack_president",
    rule:{name:"V 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 2장 가져간다."},
    skills:[{name:"맞습니다 맞고요", cost:{blue:2}, description:"40 피해", effects:[{type:"damage",amount:40}]},{name:"응딩이 뒤에서 숨어가지고", cost:{blue:4}, description:"동전 뒤집기를 시작하여 앞면이 나올 때마다 +20. 뒷면이 나오면 종료합니다. 기본 90 피해", effects:[{type:"repeatCoinBonusUntilTails",headsBonus:20},{type:"damage",amount:90}]}] },
  { id:"character_07", name:"김대중", type:"character", rarity:"RR", attribute:"blue", hp:170, weakness:"pink", resistance:"green", retreatCost:{any:3}, packId:"pack_president",
    skills:[{name:"go down fighting", cost:{blue:2}, description:"40 피해", effects:[{type:"damage",amount:40}]},{name:"내고향 신안", cost:{blue:3}, description:"동전이 뒷면이면 내 HP -10. 기본 80 피해", effects:[{type:"coinFlipSelfDamageOnTails",amount:10},{type:"damage",amount:80}]}] },
  { id:"character_08", name:"김영삼", type:"character", rarity:"R", attribute:"orange", hp:170, weakness:"blue", resistance:"red", retreatCost:{any:3}, packId:"pack_president",
    skills:[{name:"하나회 척결", cost:{orange:1, any:1}, description:"상대 인물 카드가 검은색 속성이라면 추가 피해 20. 기본 40 피해", effects:[{type:"bonusDamageIfEnemyAttribute",attribute:"black",amount:20},{type:"damage",amount:40}]},{name:"IMF", cost:{orange:3}, description:"상대의 토큰 중 원하는 토큰 1개를 가져옵니다. 60 피해", effects:[{type:"stealToken",amount:1},{type:"damage",amount:60}]}] },
  { id:"character_09", name:"노태우", type:"character", rarity:"R", attribute:"black", hp:190, weakness:"brown", resistance:"blue", retreatCost:{any:3}, packId:"pack_president", tags:["criminal_record"],
    skills:[{name:"범죄와의 전쟁", cost:{black:2}, description:"상대 인물 카드가 갈색일 경우 추가 피해 20. 기본 40 피해", effects:[{type:"bonusDamageIfEnemyAttribute",attribute:"brown",amount:20},{type:"damage",amount:40}]},{name:"신군부", cost:{black:1, any:2}, description:"70 피해", effects:[{type:"damage",amount:70}]}] },
  { id:"character_10", name:"전두환", type:"character", rarity:"SSR", attribute:"black", hp:250, weakness:"brown", resistance:"blue", retreatCost:{any:3}, packId:"pack_president", tags:["criminal_record"],
    rule:{name:"V 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 2장 가져간다."},
    trait:{name:"광주는", description:"20 피해. 상대 인물 카드가 파란색, 분홍색, 갈색, 노란색이라면 +30", effects:[{type:"bonusDamageIfEnemyAttributeIn",attributes:["blue","pink","brown","yellow"],amount:30},{type:"damage",amount:20}]},
    skills:[{name:"진압하지 않을 수 없잖아요", cost:{black:2, any:2}, description:"동전을 최대 3번 뒤집습니다. 뒷면이 나오면 추가 피해 20 후 종료합니다. 앞면 2번 뒤 뒷면이면 추가 피해 60, 앞면 3번이면 추가 피해 80. 기본 90 피해", effects:[{type:"streakCoinDamageModifier",maxFlips:3,headsBonuses:[0,0,40,80],tailsBonus:20},{type:"damage",amount:90}]}] },
  { id:"character_11", name:"최규하", type:"character", rarity:"U", attribute:"gray", hp:150, weakness:"black", resistance:"yellow", retreatCost:{any:3}, packId:"pack_president",
    trait:{name:"과도기", description:"10 피해. 이 카드가 두 번째로 놓인 인물 카드라면 추가 피해 10", effects:[{type:"bonusDamageIfCharacterUseNumber",useNumber:2,amount:10},{type:"damage",amount:10}]},
    skills:[{name:"정치적 야욕", cost:{gray:2}, description:"50 피해", effects:[{type:"damage",amount:50}]}] },
  { id:"character_12", name:"박정희", type:"character", rarity:"SSR", attribute:"black", hp:260, weakness:"brown", resistance:"blue", retreatCost:{any:3}, packId:"pack_president",
    rule:{name:"V 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 2장 가져간다."},
    trait:{name:"조국과 민족을 위하여", description:"10 피해. 검은색 토큰을 1개 획득합니다.", effects:[{type:"addToken",color:"black",amount:1},{type:"damage",amount:10}]},
    skills:[{name:"경제 개발 5개년 계획", cost:{black:5}, description:"동전이 앞면이면 +10. 기본 140 피해", effects:[{type:"coinFlipDamageModifier",headsMultiplier:1,headsBonus:10,tailsBonus:0},{type:"damage",amount:140}]}] },
  { id:"character_13", name:"윤보선", type:"character", rarity:"U", attribute:"blue", hp:150, weakness:"black", resistance:"red", retreatCost:{any:3}, packId:"pack_president",
    trait:{name:"장면과의 갈등", description:"20 피해. 자신에게 10 피해", effects:[{type:"selfDamage",amount:10},{type:"damage",amount:20}]},
    skills:[{name:"어서오세요", cost:{blue:1, any:1}, description:"40 피해", effects:[{type:"damage",amount:40}]}] },
  { id:"character_14", name:"이승만", type:"character", rarity:"SSR", attribute:"red", hp:230, weakness:"blue", resistance:"yellow", retreatCost:{any:3}, packId:"pack_president",
    rule:{name:"V 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 2장 가져간다."},
    trait:{name:"건국 대통령", description:"30 피해. 이 특성으로 상대 인물이 죽으면 원하는 토큰 1개를 획득합니다.", effects:[{type:"gainTokenIfDefeats",amount:1},{type:"damage",amount:30}]},
    skills:[{name:"한미상호방위조약", cost:{red:3, any:1}, description:"100 피해. 이 기술을 사용하고 나서 특성을 사용할 수 있습니다.", effects:[{type:"allowTraitAfterSkill"},{type:"damage",amount:100}]}] },
  { id:"character_15", name:"도널드 트럼프", type:"character", rarity:"SR", attribute:"white", hp:180, weakness:"gray", resistance:"yellow", retreatCost:{any:3}, tags:["foreign","usa","criminal_record"],
    trait:{name:"지옥에서 돌아온 자", description:"20 피해. 이 특성으로 상대 인물 카드를 죽이면 이 카드의 체력을 20 회복합니다.", effects:[{type:"healSelfIfDefeats",amount:20},{type:"damage",amount:20}]},
    skills:[{name:"관세", cost:{white:3}, description:"상대방의 토큰 중 아무거나 1개를 흰색으로 바꿉니다. 흰색 토큰은 기술 재화가 아무 토큰일 때만 사용할 수 있습니다. 80 피해", effects:[{type:"convertEnemyToken",to:"white",amount:1},{type:"damage",amount:80}]}] },
  { id:"character_16", name:"조 바이든", type:"character", rarity:"C", attribute:"white", hp:140, weakness:"red", resistance:"blue", retreatCost:{any:3}, tags:["foreign","usa"],
    trait:{name:"치매", description:"20 피해. 이 카드에 10 피해를 주고 동전 뒤집기를 할 수 있습니다. 앞면이면 상대 인물 카드에 추가로 20 피해.", effects:[{type:"selfDamage",amount:10},{type:"coinFlipDamageModifier",headsBonus:20,tailsBonus:0},{type:"damage",amount:20}]},
    skills:[{name:"부정선거", cost:{white:2}, description:"자신의 토큰 1개를 원하는 색으로 바꿉니다. 40 피해", effects:[{type:"convertOwnTokenToActiveAttribute",amount:1},{type:"damage",amount:40}]}] },
  { id:"character_17", name:"조지 W. 부시", type:"character", rarity:"C", attribute:"white", hp:150, weakness:"brown", resistance:"blue", retreatCost:{any:3}, tags:["foreign","usa","criminal_record"],
    trait:{name:"테러와의 전쟁", description:"10 피해. 상대 인물 속성이 하얀색을 제외한 나머지 속성이라면 -10", effects:[{type:"bonusDamageUnlessEnemyAttribute",attribute:"white",amount:-10},{type:"damage",amount:10}]},
    skills:[{name:"서브프라임 모기지", cost:{white:2}, description:"상대 인물 카드의 체력이 100 이하인 경우 피해 +10. 기본 50 피해", effects:[{type:"bonusDamageIfEnemyHpAtMost",threshold:100,amount:10},{type:"damage",amount:50}]}] },
  { id:"character_18", name:"장동혁", type:"character", rarity:"RR", attribute:"red", hp:180, weakness:"orange", resistance:"pink", retreatCost:{any:3},
    skills:[{name:"보수 재건", cost:{any:1}, description:"20 피해. 바로 다음 턴의 자신의 기술 피해량이 1.5배가 됩니다.", effects:[{type:"nextTurnSkillDamageMultiplier",amount:1.5},{type:"damage",amount:20}]},{name:"연임", cost:{red:2, any:1}, description:"장동혁 당대표의 연임을 응원합니다. 80 피해", effects:[{type:"damage",amount:80}]}] },
  { id:"character_19", name:"안철수", type:"character", rarity:"SR", attribute:"gray", hp:200, weakness:"orange", resistance:"blue", retreatCost:{any:3},
    trait:{name:"안초딩", description:"20 피해. 홍준표를 상대로 사용할 수 없습니다.", effects:[{type:"cannotUseAgainstName",name:"홍준표"},{type:"damage",amount:20}]},
    skills:[{name:"단일화", cost:{gray:4}, description:"손에 있는 인물 카드 1장을 선택해 제거할 수 있습니다. 제거했다면 자신의 카드를 50 회복합니다. 100 피해", effects:[{type:"optionalDiscardCharacterFromHand"},{type:"healIfDiscarded",amount:50},{type:"damage",amount:100}]}] },
  { id:"character_20", name:"유정복", type:"character", rarity:"U", attribute:"red", hp:180, weakness:"pink", resistance:"blue", retreatCost:{any:3},
    trait:{name:"(전)인천광역시장", description:"10 피해. 동전 뒤집기를 하여 앞면이면 이 카드의 체력을 20 회복, 뒷면이면 상대 인물 카드에 추가로 20 피해", effects:[{type:"coinFlipHealSelfOrBonusDamage",headsHeal:20,tailsBonus:20},{type:"damage",amount:10}]},
    skills:[{name:"인천의 꿈 대한민국의 미래", cost:{red:3, any:1}, description:"이 카드의 체력을 50 회복합니다. 70 피해", effects:[{type:"heal",amount:50},{type:"damage",amount:70}]}] },
  { id:"character_21", name:"오세훈", type:"character", rarity:"RR", attribute:"orange", hp:180, weakness:"purple", resistance:"red", retreatCost:{any:3},
    trait:{name:"서울특별시장", description:"20 피해. 다음 차례에 원하는 토큰 1개를 더 받습니다.", effects:[{type:"nextTurnExtraToken",amount:1},{type:"damage",amount:20}]},
    skills:[{name:"오동석 연합", cost:{orange:2, any:2}, description:"오세훈+한동훈+이준석. 100 피해", effects:[{type:"damage",amount:100}]}] },
  { id:"character_22", name:"주진우", type:"character", rarity:"RR", attribute:"red", hp:180, weakness:"blue", resistance:"pink", retreatCost:{any:3},
    skills:[{name:"쓰레드 업로드", cost:{red:1}, description:"30 피해", effects:[{type:"damage",amount:30}]},{name:"주진우의 5후 LIVE", cost:{red:3, any:1}, description:"동전 뒤집기를 5번 하여 앞면이 나온 횟수 × 10의 피해를 추가로 입힙니다. 기본 80 피해", effects:[{type:"fixedCoinFlipsDamageBonus",flips:5,headsBonus:10},{type:"damage",amount:80}]}] },
  { id:"character_23", name:"이회창", type:"character", rarity:"RR", attribute:"orange", hp:180, weakness:"blue", resistance:"red", retreatCost:{any:3},
    trait:{name:"대통령빼고 다해본 자", description:"20 피해. 대통령 팩 소속 인물 카드에게는 -20", effects:[{type:"bonusDamageIfEnemyPack",packId:"pack_president",amount:-20},{type:"damage",amount:20}]},
    skills:[{name:"한나라당의 원로", cost:{orange:3, any:1}, description:"근본. 110 피해", effects:[{type:"damage",amount:110}]}] },
  { id:"character_24", name:"홍준표", type:"character", rarity:"SR", attribute:"orange", hp:180, weakness:"blue", resistance:"red", retreatCost:{any:3}, tags:["criminal_record"],
    trait:{name:"자유한국당", description:"20 피해. 빨간색 속성의 상대 인물 카드에게 -20", effects:[{type:"bonusDamageIfEnemyAttribute",attribute:"red",amount:-20},{type:"damage",amount:20}]},
    skills:[{name:"홍준표 2번", cost:{orange:2, red:1}, description:"홍준표 2번 홍준표 2번 당당한 대통령 홍준표 2번 홍준표 2번 서민의 대통령 홍준표 2번. 90 피해", effects:[{type:"damage",amount:90}]}] },
  { id:"character_25", name:"정청래", type:"character", rarity:"RR", attribute:"blue", hp:180, weakness:"pink", resistance:"red", retreatCost:{any:3}, tags:["criminal_record"],
    skills:[{name:"짜장면 먹기", cost:{blue:2}, description:"저렇게 짜장면을 먹어서 주변에 다 튄다. 40 피해", effects:[{type:"damage",amount:40}]},{name:"폭탄 테러하기", cost:{blue:3, any:1}, description:"상대 인물 카드 체력이 최대 체력 기준 50% 이상이라면 추가 피해 20. 기본 80 피해", effects:[{type:"bonusDamageIfEnemyHpRatioAtLeast",ratio:.5,amount:20},{type:"damage",amount:80}]}] },
  { id:"character_26", name:"김민석", type:"character", rarity:"SR", attribute:"pink", hp:190, weakness:"green", resistance:"blue", retreatCost:{any:3}, tags:["criminal_record"],
    skills:[{name:"사전투표율 맞추기", cost:{pink:2}, description:"상대의 손패 중 카드 한 장을 뒷면으로 고른다. 속성을 맞추면 추가 피해 40. 기본 20 피해", effects:[{type:"guessRandomHandCardAttributeBonus",amount:40},{type:"damage",amount:20}]},{name:"돈 안 갚고 구라치기", cost:{pink:3}, description:"상대에게서 원하는 토큰 한 개를 가져온다. 동전 던지기를 선택할 수 있으며, 앞면이 나오면 추가 피해 20 및 토큰 한 개를 더 가져온다. 뒷면이 나오면 자신에게 -20. 기본 60 피해", effects:[{type:"stealToken",amount:1},{type:"coinFlipBonusDamageStealTokenOrSelfDamage",optional:true,headsBonus:20,headsStealToken:1,tailsSelfDamage:20},{type:"damage",amount:60}]}] },
  { id:"character_27", name:"정민철", type:"character", rarity:"C", attribute:"pink", hp:160, weakness:"blue", resistance:"orange", retreatCost:{any:3},
    trait:{name:"글 싸지르기", description:"10 피해. 동전 던지기를 하여 앞면이 나오면 자신의 체력을 10 회복합니다.", effects:[{type:"coinFlipHealSelfOrBonusDamage",headsHeal:10,tailsBonus:0},{type:"damage",amount:10}]},
    skills:[{name:"정민철의 이거 진짜예요?", cost:{pink:2, any:1}, description:"동전 던지기를 5번 하여 뒷면이 나온 횟수 × 20의 피해를 자신에게 주고, 앞면이 나온 횟수 × 10의 피해를 추가로 입힙니다. 기본 80 피해", effects:[{type:"coinFlipsDamageBonusAndSelfDamage",flips:5,headsBonus:10,tailsSelfDamage:20},{type:"damage",amount:80}]}] },
  { id:"character_28", name:"안규백", type:"character", rarity:"R", attribute:"pink", hp:160, weakness:"red", resistance:"yellow", retreatCost:{any:3},
    trait:{name:"탈영", description:"20 피해. 이 특성을 사용하면 이번 턴에만 비용 없이 즉시 후퇴할 수 있습니다.", effects:[{type:"allowFreeRetreatThisTurn"},{type:"damage",amount:20}]},
    skills:[{name:"방첩사 폐지", cost:{pink:3}, description:"자신에게도 10 피해. 100 피해", effects:[{type:"damage",amount:100},{type:"selfDamage",amount:10}]}] },
  { id:"character_29", name:"이준석", type:"character", rarity:"SR", attribute:"orange", hp:170, weakness:"blue", resistance:"orange", retreatCost:{any:2},
    trait:{name:"국힘의 귀환자", description:"상대 인물 카드가 파란색 속성이라면 다음 턴의 자신의 기술 피해가 추가 피해 20을 얻습니다.", effects:[{type:"nextTurnSkillDamageBonusIfEnemyAttribute",attribute:"blue",amount:20}]},
    skills:[{name:"퍼스트펭권", cost:{orange:2, any:1}, description:"펭귄 밥을 주며 정치자금을 강탈한다. 상대에게서 원하는 토큰 1개를 가져옵니다. 80 피해", effects:[{type:"stealToken",amount:1},{type:"damage",amount:80}]}] },
  { id:"character_30", name:"유승민", type:"character", rarity:"C", attribute:"orange", hp:150, weakness:"red", resistance:"blue", retreatCost:{any:3},
    trait:{name:"개혁보수의 아버지", description:"10 피해. 상대가 주황색 속성이 아니라면 추가 피해 10", effects:[{type:"bonusDamageUnlessEnemyAttribute",attribute:"orange",amount:10},{type:"damage",amount:10}]},
    skills:[{name:"새보갤의 갤주", cost:{orange:3}, description:"이 기술을 사용할 때 동전 뒤집기를 하여 앞면이 나오면 상대 인물 카드에게 추가 피해 10. 기본 80 피해", effects:[{type:"coinFlipDamageModifier",headsBonus:10,tailsBonus:0},{type:"damage",amount:80}]}] },
  { id:"character_31", name:"전한길", type:"character", rarity:"C", attribute:"purple", hp:160, weakness:"blue", resistance:"pink", retreatCost:{any:2},
    description:"강사 출신 정치인. 보수정당의 회의감을 느껴 현재는 탈당했다.",
    trait:{name:"윤어게인", oncePerActive:true, description:"이 특성은 이 카드가 필드에 나온 후 한 번만 사용할 수 있습니다. 자신의 트래쉬에서 윤석열 카드 한 장을 자신의 덱으로 되돌리고 덱을 셔플합니다.", effects:[{type:"recoverCharacterFromTrashToDeck",name:"윤석열"}]},
    skills:[{name:"한미동맹", cost:{purple:1, any:1}, description:"상대의 필드에 있는 외국 정치인의 수만큼 추가 피해 20. 기본 40 피해", effects:[{type:"bonusDamageForEnemyTag",tag:"foreign",amount:20},{type:"damage",amount:40}]}] },
  { id:"character_32", name:"찰리 커크", type:"character", rarity:"R", attribute:"white", hp:130, weakness:"white", resistance:"blue", retreatCost:{any:2}, tags:["foreign"],
    description:"암살만이 그의 토론을 막을 수 있습니다.",
    skills:[{name:"트럼프의 후계자", cost:{white:1}, description:"동전을 한 번 던져서 앞면이 나오면 상대 인물 카드에게 피해 40", effects:[{type:"coinFlipDamageModifier",headsBonus:40,tailsBonus:0},{type:"damage",amount:0}]},{name:"끝장 토론", cost:{white:3}, description:"상대 필드 위의 카드 한 장을 상대 덱으로 되돌리고 덱을 셔플합니다.", effects:[{type:"sendEnemyActiveToDeck"}]}] },
  { id:"character_33", name:"박원순", type:"character", rarity:"SR", attribute:"green", hp:180, weakness:"red", resistance:"purple", retreatCost:{any:3},
    description:"단지 자기 비서의 냄새를 맡고 싶은 중년",
    trait:{name:"냄새맡기", description:"상대의 냄새에 취해 아무 토큰 하나를 획득한다.", effects:[{type:"addToken",color:"any",amount:1}]},
    skills:[{name:"섹스를 알려주겠다", cost:{any:5}, description:"유흥에 취해 자신의 지식을 공유한다. 120 피해", effects:[{type:"damage",amount:120}]}] },
  { id:"character_34", name:"문재앙 VMAX", type:"character", stage:"vmax", evolvesFrom:"character_03", rarity:"HR", attribute:"blue", hp:400, weakness:"yellow", resistance:"red", retreatCost:{any:4}, tags:["criminal_record"],
    description:"문재인 V에서 진화",
    rule:{name:"VMAX 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 3장 가져간다."},
    skills:[{name:"집값 올리기", cost:{blue:1, any:1}, description:"청년들의 미래가 무너진다. 상대의 배틀 카드가 기술을 사용하는 데 필요한 에너지를 2개 추가한다. 110 피해", effects:[{type:"increaseEnemySkillCostNextTurn",amount:2},{type:"damage",amount:110}]},{name:"내친구김정은", cost:{blue:5}, description:"대한민국의 주적은 북한이 아니다. 모든 필드에 있는 북한 태그가 없는 정치인 수만큼 추가 피해 100. 기본 250 피해", effects:[{type:"bonusDamageForActiveCardsWithoutTag",tag:"north_korea",amount:100},{type:"damage",amount:250}]}] },
  { id:"character_35", name:"블라디미르 푸틴", type:"character", stage:"v", rarity:"SSR", attribute:"white", hp:250, weakness:"white", resistance:"blue", retreatCost:{any:4}, tags:["foreign","russia"],
    rule:{name:"V 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 2장 가져간다."},
    trait:{name:"죽음을 부르는 자", description:"체력이 20 이하인 상대 인물 카드를 처형합니다.", effects:[{type:"defeatIfHpAtOrBelow",threshold:20}]},
    skills:[{name:"우크라이나 폭격", cost:{white:4}, description:"상대 카드가 미국 소속이 아니라면 추가 피해 20. 기본 130 피해", effects:[{type:"bonusDamageUnlessEnemyTag",tag:"usa",amount:20},{type:"damage",amount:130}]}] },
  { id:"character_36", name:"찢재명 VMAX", type:"character", stage:"vmax", evolvesFrom:"character_01", rarity:"HR", attribute:"pink", hp:400, weakness:"blue", resistance:"purple", retreatCost:{any:3}, tags:["criminal_record"],
    description:"이재명 V에서 진화",
    rule:{name:"VMAX 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 3장 가져간다."},
    skills:[{name:"언론통제", cost:{green:1, pink:1, any:1}, description:"상대의 트래쉬에 있는 정켓몬의 수만큼 80 피해를 줍니다.", effects:[{type:"damageByEnemyTrashCharacters",amount:80}]},{name:"중국무비자입국", cost:{pink:6}, description:"대한민국은 이제 중국이다. 나라를 팔아 데미지를 올렸다. 분홍 토큰 1개를 트래쉬합니다. 500 피해", effects:[{type:"damage",amount:500}]}] },
  { id:"strategy_11", name:"아베 신조", type:"strategy", rarity:"RR", description:"자신의 인물 카드 HP가 40 이하라면 HP를 50 회복합니다.", effects:[{type:"healIfSelfHpAtMost",threshold:40,amount:50}] },
  { id:"character_37", name:"손석희", type:"character", rarity:"R", attribute:"pink", hp:140, weakness:"orange", resistance:"white", retreatCost:{any:1}, tags:["criminal_record"],
    skills:[{name:"우리 혜란이는", cost:{any:1}, description:"스튜디오의 분위기를 푼다. 20 피해", effects:[{type:"damage",amount:20}]},{name:"기자 폭행", cost:{pink:2, any:1}, description:"상대 인물 카드가 국힘팩 소속 정치인이라면 추가 피해 20. 기본 50 피해", effects:[{type:"bonusDamageIfEnemyPack",packId:"pack_people_power",amount:20},{type:"damage",amount:50}]}] },
  { id:"character_38", name:"문석열", type:"character", stage:"v", rarity:"SSR", attribute:"blue", hp:260, weakness:"blue", resistance:"gray", retreatCost:{any:4},
    rule:{name:"V 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 2장 가져간다."},
    trait:{name:"문자쿠", auto:true, description:"자동 특성. 배치 직후와 매 턴 시작 시 적용됩니다. 체력이 80 초과이면 윤석열로 취급하고 속성을 빨강으로 바꿉니다. 체력이 80 이하이면 문재인으로 취급하고 속성을 파랑으로 바꿉니다.", effects:[{type:"transformSelfByHp",threshold:80,aboveName:"윤석열",aboveAttribute:"red",aboveTags:["conservative"],belowName:"문재인",belowAttribute:"blue",belowTags:["democratic"]}]},
    skills:[{name:"적폐청산", cost:{red:3}, description:"상대 인물 카드가 주황색 또는 빨강 속성이라면 추가 피해 40. 기본 100 피해", effects:[{type:"bonusDamageIfEnemyAttributeIn",attributes:["orange","red"],amount:40},{type:"damage",amount:100}]}] },
  { id:"character_39", name:"제프리 엡스타인", type:"character", rarity:"R", attribute:"white", hp:130, weakness:"yellow", resistance:"gray", retreatCost:{any:2}, tags:["foreign","criminal_record"],
    description:"엡스타인 아일랜드의 주장. 수많은 특권층의 약점을 쥐고 있다.",
    skills:[{name:"엡스타인 리스트", cost:{white:1}, description:"상대 손패의 카드 한 장을 뒷면으로 고른 뒤 확인합니다.", effects:[{type:"revealChosenEnemyHand"}]},{name:"비밀 섬으로의 초대", cost:{white:3}, description:"필드에 있는 하양 속성 카드 수만큼 추가 피해 20. 기본 40 피해", effects:[{type:"bonusDamageForActiveCardsWithAttribute",attribute:"white",amount:20},{type:"damage",amount:40}]}] },
  { id:"character_40", name:"시진핑", type:"character", stage:"v", rarity:"SSR", attribute:"white", hp:200, weakness:"white", resistance:"pink", retreatCost:{any:3}, tags:["foreign","china"],
    rule:{name:"V 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 2장 가져간다."},
    trait:{name:"검열 시스템", oncePerActive:true, description:"이 카드가 필드에 나온 후 한 번만 사용할 수 있습니다. 상대 손패에 있는 모든 전략 카드를 상대 덱으로 되돌리고 셔플합니다.", effects:[{type:"returnEnemyHandStrategiesToDeck"}]},
    skills:[{name:"만장일치 3연임", cost:{white:3}, description:"상대 필드의 인물 카드 1장을 지정하여 반대표를 강탈합니다. 반대표 강탈은 실제 효과가 없습니다. 다음 턴 상대는 행동할 수 없습니다. 100 피해", effects:[{type:"blockOpponentNextAction"},{type:"damage",amount:100}]}] },
  { id:"character_41", name:"엠마뉘엘 마크롱", type:"character", rarity:"R", attribute:"white", hp:130, weakness:"yellow", resistance:"gray", retreatCost:{any:2}, tags:["foreign"],
    description:"프랑스 역대 최연소 대통령. 고등학교 선생과 결혼했다.",
    skills:[{name:"싸대기 맞기", cost:{white:2}, description:"이 카드의 체력을 40 회복합니다.", effects:[{type:"heal",amount:40}]},{name:"25살 연상 누나", cost:{white:3}, description:"60 피해", effects:[{type:"damage",amount:60}]}] },
  { id:"character_42", name:"전용기", type:"character", rarity:"C", attribute:"pink", hp:160, weakness:"purple", resistance:"blue", retreatCost:{any:3},
    skills:[{name:"민주파출소", cost:{pink:2}, description:"극우 세력 척결. 40 피해", effects:[{type:"damage",amount:40}]},{name:"최고위원 전용기", cost:{pink:3, any:1}, description:"정민철에게는 추가 피해 60. 그 외의 파랑 속성 인물 카드에 추가 피해 40. 기본 60 피해", effects:[{type:"bonusDamageIfEnemyName",name:"정민철",amount:60},{type:"bonusDamageIfEnemyAttributeExceptName",attribute:"blue",name:"정민철",amount:40},{type:"damage",amount:60}]}] },
  { id:"character_43", name:"유시민", type:"character", rarity:"U", attribute:"blue", hp:140, weakness:"blue", resistance:"pink", retreatCost:{any:3}, tags:["criminal_record"],
    trait:{name:"노짱 베프", description:"노무현 카드를 이 카드에 덮어씌울 수 있다(진화와 같은 방식). 단 카드 카운트는 증가하지 않는다. 노무현이 덮어진 채로 죽는다면 이 카드도 같이 제거한다. 카드는 하나만 제거된 것으로 간주한다.", effects:[{type:"evolveSelfFromHandWithoutUseCount",cardId:"character_06"}]},
    skills:[{name:"쁘락치 사건", cost:{blue:2}, description:"카드 덱에서 한 장을 손으로 가져온다. 30 피해", effects:[{type:"draw",amount:1},{type:"damage",amount:30}]}] },
  { id:"character_44", name:"김어준", type:"character", rarity:"C", attribute:"blue", hp:160, weakness:"orange", resistance:"pink", retreatCost:{any:3}, tags:["criminal_record"],
    trait:{name:"개털 날리기", description:"털보답게 주변에 털을 흩날린다. 10 피해", effects:[{type:"damage",amount:10}]},
    skills:[{name:"뉴스공장", cost:{blue:3}, description:"상대 속성이 분홍색이면 추가 피해 20. 그 외인 경우 동전 던지기를 하여 앞면이면 추가 피해 10. 기본 60 피해", effects:[{type:"bonusDamageIfEnemyAttribute",attribute:"pink",amount:20},{type:"coinFlipBonusDamageUnlessEnemyAttribute",attribute:"pink",headsBonus:10},{type:"damage",amount:60}]}] },
  { id:"character_45", name:"최민희", type:"character", rarity:"U", attribute:"blue", hp:170, weakness:"red", resistance:"pink", retreatCost:{any:3}, tags:["criminal_record"],
    skills:[{name:"유사 과방위원장", cost:{blue:1, any:1}, description:"30 피해", effects:[{type:"damage",amount:30}]},{name:"황금똥을 누는 아이", cost:{blue:2, any:2}, description:"사이비 유사 과학자. 90 피해", effects:[{type:"damage",amount:90}]}] },
  { id:"character_46", name:"박찬대", type:"character", rarity:"R", attribute:"pink", hp:130, weakness:null, resistance:null, retreatCost:{any:3},
    trait:{name:"코파주기", treatAsStrategy:true, description:"이 카드를 전략 카드로 취급할 수 있다. 카운트 소비 없이 손패에서 인물 카드를 내려놓고, 이 카드는 제거한다. 제거한 카드 카운트도 늘어나지 않지만 손패에는 1장이 들어온다.", effects:[{type:"playHandCharacterAsStrategyNoCount",excludeCardId:"character_46"}]},
    effects:[{type:"playHandCharacterAsStrategyNoCount",excludeCardId:"character_46"}],
    skills:[{name:"독립운동가가 22촌", cost:{pink:4}, description:"제작자도 독립운동가가 22촌이다. 90 피해", effects:[{type:"damage",amount:90}]}] },
  { id:"character_47", name:"이용우", type:"character", rarity:"C", attribute:"pink", hp:150, weakness:"gray", resistance:"yellow", retreatCost:{any:3},
    skills:[{name:"현수막 붙이기", cost:{pink:2}, description:"동전 던지기를 하여 연속 2번 앞면이 나오면 분홍색 토큰 1개 획득. 30 피해", effects:[{type:"fixedCoinFlipsAllHeadsAddToken",flips:2,color:"pink",amount:1},{type:"damage",amount:30}]},{name:"노란봉투법", cost:{pink:3, any:1}, description:"상대 속성이 노란색이면 추가 피해 20. 기본 80 피해", effects:[{type:"bonusDamageIfEnemyAttribute",attribute:"yellow",amount:20},{type:"damage",amount:80}]}] },
  { id:"character_48", name:"심상정", type:"character", rarity:"R", attribute:"yellow", hp:180, weakness:"blue", resistance:"orange", retreatCost:{any:3}, tags:["female","criminal_record"],
    trait:{name:"정의당의 희망", description:"아쉽게도 22대 총선에서 탈락! 20 피해", effects:[{type:"damage",amount:20}]},
    skills:[{name:"뒤를 부탁한다 권영국", cost:{yellow:3}, description:"이 기술을 쓴 후 이 카드를 제거하고(제거 카운트는 발동) 권영국 카드를 배치할 수 있다. 배치한 카드는 특성/기술을 사용할 수 있다. 10 피해", effects:[{type:"damage",amount:10},{type:"replaceSelfWithHandCharacter",cardId:"character_49",summonedBy:"character_48",allowAction:true}]}] },
  { id:"character_49", name:"권영국", type:"character", rarity:"C", attribute:"yellow", hp:150, weakness:"orange", resistance:"black", retreatCost:{any:3}, tags:["criminal_record"],
    trait:{name:"물구나무 서기", description:"심상정의 특성으로 배치되었다면 게임 중 영구적으로 이 특성에 추가 피해 10. 10 피해", effects:[{type:"bonusDamageIfSummonedBy",cardId:"character_48",amount:10},{type:"damage",amount:10}]},
    skills:[{name:"레드 카드 선고", cost:{yellow:2}, description:"상대 속성이 빨강이라면, 동전 뒤집기를 선택할 수 있다. 앞면이라면 추가 피해 70, 뒷면이면 자신에게 -60. 기본 40 피해", effects:[{type:"coinFlipBonusOrSelfDamageIfEnemyAttribute",attribute:"red",optional:true,headsBonus:70,tailsSelfDamage:60},{type:"damage",amount:40}]}] },
  { id:"character_50", name:"이석기", type:"character", rarity:"U", attribute:"brown", hp:160, weakness:"red", resistance:"yellow", retreatCost:{any:3}, tags:["criminal_record"],
    trait:{name:"통진당", description:"간첩당. 20 피해", effects:[{type:"damage",amount:20}]},
    skills:[{name:"내란 선동", cost:{brown:3}, description:"내란을 일으켜 상대 인물 카드를 즉시 제거한다. 이 카드도 즉시 제거한다.", effects:[{type:"defeatEnemyAndSelf"}]}] },
  { id:"character_51", name:"김재연", type:"character", rarity:"C", attribute:"brown", hp:160, weakness:"red", resistance:"yellow", retreatCost:{any:3}, tags:["criminal_record"],
    trait:{name:"진보당", description:"상대에게 갈색 토큰을 한 개 뺏어온다. 없을 경우 적용할 수 없다.", effects:[{type:"stealSpecificToken",color:"brown",amount:1}]},
    skills:[{name:"삭발", cost:{brown:2, any:1}, description:"왜 한거지. 70 피해", effects:[{type:"damage",amount:70}]}] },
  { id:"character_52", name:"황교안", type:"character", rarity:"RR", attribute:"purple", hp:170, weakness:"red", resistance:"brown", retreatCost:{any:3},
    trait:{name:"삭발", description:"10 피해. 상대 인물 카드가 보라, 빨강 속성이 아니라면 추가 피해 10", effects:[{type:"bonusDamageIfEnemyAttributeNotIn",attributes:["purple","red"],amount:10},{type:"damage",amount:10}]},
    skills:[{name:"자유와 혁신", cost:{purple:2, any:2}, description:"상대 인물 카드가 빨강 속성이라면 추가 피해 10. 동전이 앞면이면 추가 피해 20, 뒷면이면 상대 인물 카드 HP를 20 회복합니다. 기본 90 피해", effects:[{type:"bonusDamageIfEnemyAttribute",attribute:"red",amount:10},{type:"coinFlipBonusDamageOrHealEnemy",headsBonus:20,tailsHealEnemy:20},{type:"damage",amount:90}]}] },
  { id:"character_53", name:"나경원", type:"character", rarity:"RR", attribute:"red", hp:180, weakness:"green", resistance:"blue", retreatCost:{any:3},
    skills:[{name:"빠루", cost:{red:2}, description:"상대 인물 카드가 파랑 또는 분홍 속성이라면 추가 피해 20. 기본 40 피해", effects:[{type:"bonusDamageIfEnemyAttributeIn",attributes:["blue","pink"],amount:20},{type:"damage",amount:40}]},{name:"문재인은 김정은 대변인", cost:{red:4}, description:"문재인에게 추가 피해 30. 기본 90 피해", effects:[{type:"bonusDamageIfEnemyName",name:"문재인",amount:30},{type:"damage",amount:90}]}] },
  { id:"character_54", name:"김문수", type:"character", rarity:"SR", attribute:"red", hp:200, weakness:"yellow", resistance:"pink", retreatCost:{any:3}, tags:["criminal_record"],
    trait:{name:"나 도지사 김문순데", description:"트래쉬의 인물 카드 1장을 손패로 가져옵니다.", effects:[{type:"recoverCharacterFromTrash"}]},
    skills:[{name:"기가문수", cost:{red:3, any:1}, description:"상대의 빨강 토큰 1개를 가져옵니다. 동전이 앞면이면 상대 토큰 1개를 추가로 가져옵니다. 100 피해", effects:[{type:"stealSpecificToken",color:"red",amount:1},{type:"coinFlipStealToken",amount:1},{type:"damage",amount:100}]}] },
  { id:"character_55", name:"허경영 V", type:"character", stage:"v", rarity:"SSR", attribute:"brown", hp:250, weakness:"gray", resistance:"yellow", retreatCost:{any:3}, tags:["criminal_record"],
    rule:{name:"V 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 2장 가져간다."},
    trait:{name:"공중부양", description:"10 피해. 동전이 앞면이면 상대 토큰 1개를 가져옵니다.", effects:[{type:"coinFlipStealToken",amount:1},{type:"damage",amount:10}]},
    skills:[{name:"내 눈을 바라봐", cost:{yellow:1, any:3}, description:"원하면 내 갈색 토큰을 모두 트래쉬하고 그 수만큼 덱에서 카드를 보충한 뒤, 손패를 모두 트래쉬하여 버린 카드 수 × 30만큼 추가 피해를 줍니다. 기본 90 피해", effects:[{type:"discardOwnTokensDrawThenDiscardHandBonusDamage",color:"brown",amount:30,optional:true},{type:"damage",amount:90}]}] },
  { id:"character_56", name:"김상욱", type:"character", rarity:"U", attribute:"pink", hp:160, weakness:"brown", resistance:"red", retreatCost:{any:3},
    trait:{name:"변절자", description:"10 피해. 상대 인물 카드가 빨강 또는 주황 속성이라면 추가 피해 10", effects:[{type:"bonusDamageIfEnemyAttributeIn",attributes:["red","orange"],amount:10},{type:"damage",amount:10}]},
    skills:[{name:"약간 맛이간 사람", cost:{pink:1, blue:1, any:2}, description:"동전 2개를 던집니다. 앞면 수만큼 분홍 토큰, 뒷면 수만큼 파랑 토큰을 얻습니다. 80 피해", effects:[{type:"coinFlipAddTokensByResult",flips:2,headsColor:"pink",tailsColor:"blue"},{type:"damage",amount:80}]}] },
  { id:"character_57", name:"서영교", type:"character", rarity:"R", attribute:"blue", hp:180, weakness:"purple", resistance:"red", retreatCost:{any:3}, tags:["criminal_record"],
    trait:{name:"서팔계", description:"10 피해. 이 카드의 최대 HP를 10 올립니다. 현재 HP는 회복하지 않습니다.", effects:[{type:"increaseMaxHp",amount:10},{type:"damage",amount:10}]},
    skills:[{name:"국회에서 소리지르기", cost:{blue:4}, description:"이 카드의 HP를 20 회복합니다. 80 피해", effects:[{type:"heal",amount:20},{type:"damage",amount:80}]}] },
  { id:"character_58", name:"그라운드 C", type:"character", rarity:"C", attribute:"red", hp:150, weakness:"purple", resistance:"brown", retreatCost:{any:3},
    trait:{name:"100만 유튜버", description:"상대의 모든 빨강 토큰을 원하는 색으로 바꿉니다. 이 카드에게 반동 30 피해. 10 피해", effects:[{type:"convertAllEnemyTokensByColor",from:"red"},{type:"selfDamage",amount:30},{type:"damage",amount:10}]},
    skills:[{name:"윤어게인", cost:{red:2, purple:1, any:1}, description:"남은 빨강 토큰을 추가로 모두 소모하고, 소모한 수 × 30만큼 추가 피해. 기본 60 피해", effects:[{type:"bonusDamageForOwnTokenColorThenSpend",color:"red",amount:30},{type:"damage",amount:60}]}] },
  { id:"character_59", name:"이진숙", type:"character", rarity:"R", attribute:"red", hp:170, weakness:"blue", resistance:"pink", retreatCost:{any:3},
    skills:[{name:"진실을 찾아서", cost:{red:1, any:3}, description:"파랑 또는 분홍 속성의 상대 인물 카드만 뒷면으로 만듭니다. 뒷면 카드는 비활성화되며, 자신의 턴에 동전을 던져 앞면이 나오면 다시 활성화된 뒤 턴이 끝납니다.", effects:[{type:"turnEnemyActiveFaceDownIfEnemyAttributeIn",attributes:["blue","pink"]}]},{name:"518 토론회 개최", cost:{red:3, any:1}, description:"80 피해", effects:[{type:"damage",amount:80}]}] },
  { id:"character_60", name:"한동훈", type:"character", rarity:"U", attribute:"gray", hp:150, weakness:"red", resistance:"purple", retreatCost:{any:3},
    trait:{name:"배신자", description:"이 카드의 속성을 원하는 색으로 바꿉니다.", effects:[{type:"changeSelfAttribute"}]},
    skills:[{name:"친한파 붕기", cost:{gray:3, any:1}, description:"원하면 이 기술 뒤 이 카드를 트래쉬하고 추가 피해 100. 기본 60 피해", effects:[{type:"optionalDefeatSelfForBonusDamage",amount:100},{type:"damage",amount:60}]}] },
  { id:"character_61", name:"김재섭", type:"character", rarity:"C", attribute:"orange", hp:160, weakness:"red", resistance:"brown", retreatCost:{any:3},
    trait:{name:"친한파 포섭", description:"이번 피해 계산에서 상대 인물 카드의 속성을 주황으로 취급합니다. 10 피해", effects:[{type:"treatEnemyAttributeForDamage",attribute:"orange"},{type:"damage",amount:10}]},
    skills:[{name:"도봉구 주민 맞팔", cost:{orange:2, any:2}, description:"80 피해", effects:[{type:"damage",amount:80}]}] },
  { id:"character_62", name:"호밀밭의 우원재", type:"character", rarity:"C", attribute:"orange", hp:150, weakness:"pink", resistance:"purple", retreatCost:{any:3},
    skills:[{name:"미니 다큐", cost:{orange:1, any:1}, description:"40 피해", effects:[{type:"damage",amount:40}]},{name:"강한 문제의식", cost:{orange:4}, description:"덱에서 무작위 전략 카드 1장을 손패로 가져옵니다. 100 피해", effects:[{type:"recoverRandomStrategyFromDeck"},{type:"damage",amount:100}]}] },
  { id:"character_63", name:"윤상현", type:"character", rarity:"RR", attribute:"orange", hp:180, weakness:"purple", resistance:"red", retreatCost:{any:3},
    trait:{name:"부정선거 국감위원장", description:"20 피해. 상대 인물 카드가 파랑 또는 분홍 속성이라면 피해가 10 줄어듭니다.", effects:[{type:"bonusDamageIfEnemyAttributeIn",attributes:["blue","pink"],amount:-10},{type:"damage",amount:20}]},
    skills:[{name:"부정선거의 수혜자", cost:{brown:3, any:1}, description:"내 토큰 1개를 원하는 색으로 바꿉니다. 80 피해", effects:[{type:"convertOwnTokenToChosenColor",amount:1},{type:"damage",amount:80}]}] },
  { id:"character_64", name:"조국", type:"character", rarity:"SR", attribute:"blue", hp:190, weakness:"pink", resistance:"purple", retreatCost:{any:3}, tags:["criminal_record"],
    trait:{name:"내 딸 조민", description:"10 피해. 이 카드의 속성을 원하는 색으로 바꿉니다.", effects:[{type:"changeSelfAttribute"},{type:"damage",amount:10}]},
    skills:[{name:"\"조국\"혁신당", cost:{blue:4}, description:"기본 40 피해. 동전 뒤집기를 선택할 수 있습니다. 앞면이 나오면 추가 피해 40을 얻고, 한 번 더 뒤집거나 그만둘 수 있습니다. 그만두면 누적 추가 피해를 적용합니다. 계속 뒤집다가 뒷면이 나오면 누적 추가 피해를 모두 잃고 기본 피해만 주며, 이 카드에게 반동 40 피해를 줍니다.", effects:[{type:"pushYourLuckDamageModifier",optional:true,headsBonus:40,tailsSelfDamage:40,maxFlips:8},{type:"damage",amount:40}]}] },
  { id:"character_65", name:"윤석열 VMAX", type:"character", stage:"vmax", evolvesFrom:"character_02", rarity:"HR", attribute:"red", hp:430, weakness:"orange", resistance:"blue", retreatCost:{any:4},
    description:"윤석열에서 진화",
    rule:{name:"VMAX 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 3장 가져간다."},
    skills:[{name:"반국가세력 척결", cost:{red:2}, description:"분홍, 파랑, 갈색, 초록 속성 적에게 추가 피해 30. 기본 80 피해", effects:[{type:"bonusDamageIfEnemyAttributeIn",attributes:["pink","blue","brown","green"],amount:30},{type:"damage",amount:80}]},{name:"계엄군 투입", cost:{red:4, any:1}, description:"상대가 남기길 원하는 토큰 2개를 제외하고 상대의 모든 토큰을 가져옵니다. 300 피해", effects:[{type:"stealAllTokensExceptCount",keep:2},{type:"damage",amount:300}]}] },
  { id:"character_66", name:"김정은", type:"character", rarity:"SR", attribute:"white", hp:200, weakness:"white", resistance:"blue", retreatCost:{any:3}, tags:["north_korea"],
    trait:{name:"돼지", passive:true, description:"패시브. 자신이 받는 모든 피해를 10 줄입니다.", effects:[{type:"passiveDamageReduction",amount:10}]},
    skills:[{name:"핵미사일", cost:{white:2}, description:"자신의 체력을 10 회복합니다. 50 피해", effects:[{type:"heal",amount:10},{type:"damage",amount:50}]}] },
  { id:"character_67", name:"김정일", type:"character", rarity:"U", attribute:"white", hp:160, weakness:"blue", resistance:"white", retreatCost:{any:3}, tags:["north_korea"],
    trait:{name:"남북정상회담", description:"전국민 앞에서 쇼를 한다. 10 피해", effects:[{type:"damage",amount:10}]},
    skills:[{name:"고난의 행군", cost:{white:4}, description:"자신의 최대 체력을 20 낮춥니다. 110 피해", effects:[{type:"decreaseMaxHp",amount:20},{type:"damage",amount:110}]}] },
  { id:"character_68", name:"김일성", type:"character", rarity:"U", attribute:"white", hp:160, weakness:"blue", resistance:"white", retreatCost:{any:3}, tags:["north_korea"],
    skills:[{name:"주체사상", cost:{white:2}, description:"인민들을 세뇌시킨다. 40 피해", effects:[{type:"damage",amount:40}]},{name:"625전쟁", cost:{white:4}, description:"상대 인물 카드에 북한 태그가 없다면 추가 피해 10. 기본 90 피해", effects:[{type:"bonusDamageUnlessEnemyTag",tag:"north_korea",amount:10},{type:"damage",amount:90}]}] },
  { id:"character_69", name:"노무현 VMAX", type:"character", stage:"vmax", evolvesFrom:"character_06", rarity:"HR", attribute:"blue", hp:410, weakness:"pink", resistance:"red", retreatCost:{any:4},
    description:"노무현에서 진화",
    rule:{name:"VMAX 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 3장 가져간다."},
    skills:[{name:"국정원 지하실", cost:{blue:2}, description:"하양 속성을 제외한 모든 적에게 추가 피해 30. 기본 90 피해", effects:[{type:"bonusDamageUnlessEnemyAttribute",attribute:"white",amount:30},{type:"damage",amount:90}]},{name:"운지", cost:{blue:4, any:1}, description:"상대가 문재인 또는 문재앙 VMAX라면 피해를 입히지 못하고 자신이 죽습니다. 기본 230 피해", effects:[{type:"selfDefeatAndSkipDamageIfEnemyNameIn",names:["문재인","문재앙 VMAX"]},{type:"damage",amount:230}]}] },
  { id:"character_70", name:"전땅크 VMAX", type:"character", stage:"vmax", evolvesFrom:"character_10", rarity:"HR", attribute:"black", hp:450, weakness:"orange", resistance:"blue", retreatCost:{any:4}, tags:["criminal_record"],
    description:"전두환에서 진화",
    rule:{name:"VMAX 룰", description:"이 인물이 기절한 경우 상대는 프라이즈를 3장 가져간다."},
    skills:[{name:"부대 열중 쉬어", cost:{black:2, any:1}, description:"상대 손패 카드 1장을 내 손패 카드 1장과 교환합니다. 100 피해", effects:[{type:"swapHandCardWithEnemy"},{type:"damage",amount:100}]},{name:"폭동이야", cost:{black:4, any:1}, description:"노태우 카드가 손에 있다면 트래쉬하고 추가 피해 100. 그 외 손패 1장을 트래쉬하면 추가 피해 50. 기본 300 피해", effects:[{type:"discardPreferredHandCardForBonusDamage",preferredCardId:"character_09",preferredBonus:100,fallbackBonus:50},{type:"damage",amount:300}]}] },
  { id:"character_71", name:"용혜인", type:"character", rarity:"U", attribute:"pink", hp:150, weakness:"red", resistance:"black", retreatCost:{any:3}, tags:["female","criminal_record"],
    trait:{name:"민주당 따까리", description:"동전이 앞면이면 추가 피해 20. 기본 10 피해", effects:[{type:"coinFlipDamageModifier",headsBonus:20,tailsBonus:0},{type:"damage",amount:10}]},
    skills:[{name:"기본소득", cost:{pink:2, green:1, any:1}, description:"상대의 모든 토큰을 한 턴간 압류합니다. 압류한 토큰은 그 턴 동안 사라졌다가 다시 상대에게 돌아갑니다. 70 피해", effects:[{type:"suspendEnemyTokens"},{type:"damage",amount:70}]}] },
  { id:"character_72", name:"문크예거", type:"character", rarity:"R", attribute:"blue", hp:160, weakness:"yellow", resistance:"red", retreatCost:{any:2}, tags:["criminal_record"],
    skills:[{name:"훠!!!!!!!!!", cost:{blue:1, any:1}, description:"미안하다 고맙다. 40 피해", effects:[{type:"damage",amount:40}]},{name:"등산", cost:{blue:2, any:1}, description:"우리 어린이 지구 울면 등산갑니다. 110 피해", effects:[{type:"damage",amount:110}]}] },
  { id:"character_73", name:"찢칠라", type:"character", rarity:"R", attribute:"pink", hp:80, weakness:"white", resistance:"white", retreatCost:{any:3}, tags:["criminal_record"],
    skills:[{name:"여가부 지원금", cost:{pink:1, any:1}, description:"상대 배틀 필드 카드가 여성이라면 추가 피해 10. 기본 20 피해", effects:[{type:"bonusDamageIfEnemyTag",tag:"female",amount:10},{type:"damage",amount:20}]}] },
  { id:"strategy_12", name:"탄핵", type:"strategy", rarity:"C", description:"상대의 배틀 필드에 있는 대통령팩 소속 인물을 덱으로 되돌리고 셔플합니다. 노무현은 이 카드의 효과를 받지 않습니다.", effects:[{type:"sendEnemyActiveToDeckIfPackNotName",packId:"pack_president",name:"노무현"}] },
  { id:"strategy_13", name:"국정감사", type:"strategy", rarity:"C", description:"다음 턴에 상대 필드에 있는 전과가 있는 정치인의 데미지를 50 줄입니다. 이 효과는 중복되지 않습니다.", effects:[{type:"reduceOpponentDamageNextTurnIfTag",tag:"criminal_record",amount:50,unique:true}] },
  { id:"strategy_14", name:"트럼프의 앙탈", type:"strategy", rarity:"C", description:"자신의 배틀 필드에 있는 정치인의 성별을 반대로 바꿉니다.", effects:[{type:"toggleOwnActiveGender"}] },
  { id:"strategy_15", name:"노벨평화상", type:"strategy", rarity:"C", description:"상대의 모든 토큰을 트래쉬합니다.", effects:[{type:"discardEnemyTokens"}] },
  { id:"strategy_05", name:"비선실세", type:"strategy", rarity:"C", description:"배치된 인물 카드의 기술을 한 번 더 사용할 수 있습니다.", effects:[{type:"allowExtraSkill"}] },
  { id:"strategy_06", name:"폭로", type:"strategy", rarity:"C", description:"내 인물 카드의 체력을 10 회복하고, 상대 인물 카드에게 20 고정 피해를 줍니다.", effects:[{type:"heal",amount:10},{type:"directDamage",amount:20}] },
  { id:"strategy_07", name:"유영하의 고릴라", type:"strategy", rarity:"SR", description:"다음 차례에 자신의 필드에 있는 모든 국힘 소속 인물 카드는 상대 카드로 발생한 모든 효과를 받지 않습니다.", effects:[{type:"shieldPackFromOpponentEffectsNextTurn",packId:"pack_people_power"}] },
  { id:"strategy_08", name:"경제개발 5개년 계획", type:"strategy", rarity:"SR", description:"두 가지 효과 중 하나를 선택하여 사용합니다. 1. 자신의 배틀 필드의 인물 카드 한 장에 검은색 토큰 3개를 붙입니다. 2. 자신의 트래쉬에 검은색 속성 인물 카드가 있다면 다시 손패로 가져옵니다.",
    choices:[{label:"검은색 토큰 3개 붙이기", description:"자신의 배틀 필드의 인물 카드 한 장에 검은색 토큰 3개를 붙입니다.", effects:[{type:"attachToken",color:"black",amount:3}]},{label:"검은색 인물 회수", description:"자신의 트래쉬에 검은색 속성 인물 카드가 있다면 다시 손패로 가져옵니다.", effects:[{type:"recoverCharacterFromTrash",attribute:"black"}]}],
    effects:[{type:"attachToken",color:"black",amount:3}] },
  { id:"strategy_09", name:"드럼통", type:"strategy", rarity:"C", description:"상대의 필드에 있는 HP 50 이하의 인물 카드를 트래쉬합니다. 동전을 던져서 앞면이 나오면 다시 자신의 패로 가져옵니다.", effects:[{type:"defeatIfHpAtOrBelow",threshold:50},{type:"recoverThisStrategyOnCoinHeads"}] },
  { id:"strategy_10", name:"문재인의 지하실 열쇠", type:"strategy", rarity:"R", description:"자신의 트래쉬에서 노무현 카드를 한 장 자신의 패로 가져옵니다. 단, 상대의 배틀 필드에 문재인이 나와있다면 사용할 수 없습니다.", effects:[{type:"cannotUseIfEnemyName",name:"문재인"},{type:"recoverCharacterFromTrash",name:"노무현"}] },
  { id:"strategy_16", name:"졸기", type:"strategy", rarity:"U", description:"상대는 다음 턴에 토큰을 받을 수 없습니다.", effects:[{type:"skipEnemyNextTokenGain"}] },
  { id:"strategy_17", name:"진압", type:"strategy", rarity:"SSR", description:"손패의 카드 1장을 추가로 트래쉬하면 상대 인물 카드도 즉시 트래쉬합니다.", effects:[{type:"discardAnyHandCardThenDefeatEnemy"}] },
  { id:"strategy_18", name:"48시간 무박 유세", type:"strategy", rarity:"RR", description:"자신의 인물 카드 체력을 30 깎는 대신, 이번 턴 바로 다음에 공격하는 피해량을 2배로 늘립니다.", effects:[{type:"selfDamage",amount:30},{type:"nextAttackDamageMultiplierThisTurn",amount:2},{type:"allowExtraSkill"}] },
  { id:"strategy_19", name:"기본소득", type:"strategy", rarity:"U", description:"상대 덱에서 카드 1장을 가져옵니다.", effects:[{type:"stealEnemyTopDeckCard"}] },
  { id:"strategy_20", name:"성역화", type:"strategy", rarity:"U", description:"내 인물 카드의 HP를 30 회복합니다.", effects:[{type:"heal",amount:30}] },
  { id:"strategy_21", name:"대출 규제", type:"strategy", rarity:"U", description:"바로 다음 턴 상대가 기술/특성을 사용하려면 아무 토큰 1개가 더 필요합니다.", effects:[{type:"increaseEnemyActionCostNextTurn",amount:1}] },
  { id:"strategy_22", name:"강달프", type:"strategy", rarity:"U", description:"현재 내 인물 카드는 게임 중 영구적으로 받는 피해를 10 줄입니다.", effects:[{type:"addPermanentDamageReduction",amount:10}] },
  { id:"strategy_23", name:"대법원장", type:"strategy", rarity:"U", description:"직전 상대 턴에 내 인물이 받은 공격 피해를 상대에게 반사합니다.", effects:[{type:"reflectPreviousOpponentDamage"}] },
  { id:"strategy_24", name:"여성할당제", type:"strategy", rarity:"U", description:"자신의 인물 카드가 여성이라면 HP를 40 회복합니다.", effects:[{type:"healIfSelfTag",tag:"female",amount:40}] },
  { id:"strategy_25", name:"간첩", type:"strategy", rarity:"U", description:"상대 손패 카드 2장을 확인합니다. 그중 1장은 상대에게 돌려주고, 1장은 가져온 뒤 상대는 이 카드를 쓴 사람의 덱에서 1장을 뽑습니다.", effects:[{type:"spyTwoEnemyCardsStealOneAndReplace"}] },
  { id:"strategy_26", name:"국정원", type:"strategy", rarity:"U", description:"현재 내 인물 카드의 최대 체력만 50 늘립니다. 현재 체력은 늘어나지 않습니다.", effects:[{type:"increaseMaxHp",amount:50}] },
  { id:"strategy_27", name:"지지자", type:"strategy", rarity:"U", description:"내 인물 카드는 HP를 20 회복하고, 상대 인물 카드에게 10 고정 피해를 줍니다.", effects:[{type:"heal",amount:20},{type:"directDamage",amount:10}] },
  { id:"strategy_28", name:"방명록", type:"strategy", rarity:"U", description:"이번 턴 바로 다음에 공격하는 피해를 1.5배 적용합니다. 피해량은 10의 배수가 되도록 내립니다.", effects:[{type:"nextAttackDamageMultiplierThisTurn",amount:1.5,roundDownTo:10},{type:"allowExtraSkill"}] },
  { id:"strategy_29", name:"코스피", type:"strategy", rarity:"C", description:"원하는 토큰 1개를 획득합니다.", effects:[{type:"addToken",color:"any",amount:1}] },
  { id:"strategy_30", name:"영포티", type:"strategy", rarity:"R", description:"파랑 토큰 2개 또는 분홍 토큰 2개를 획득합니다.",
    choices:[{label:"파랑 토큰 2개", description:"파랑 토큰 2개를 획득합니다.", effects:[{type:"addToken",color:"blue",amount:2}]},{label:"분홍 토큰 2개", description:"분홍 토큰 2개를 획득합니다.", effects:[{type:"addToken",color:"pink",amount:2}]}],
    effects:[{type:"addToken",color:"blue",amount:2}] },
];

const packs = [
  { id:"pack_people_power", name:"국힘 카드팩", cardIds:[], price:220, description:"국민의힘 계열 인물과 관련 전략 카드를 넣는 팩입니다." },
  { id:"pack_democratic", name:"민주당 카드팩", cardIds:[], price:240, description:"민주당 계열 인물과 관련 전략 카드를 넣는 팩입니다." },
  { id:"pack_assembly", name:"22대 국회팩", cardIds:[], price:190, description:"22대 국회 인물과 의정 활동 전략 카드를 넣는 팩입니다." },
  { id:"pack_president", name:"대통령 카드팩", cardIds:[], price:270, description:"역대·현직 대통령 카드와 대통령 관련 전략 카드를 넣는 팩입니다." },
  { id:"pack_legacy", name:"죽은 정치인 카드팩", cardIds:[], price:170, description:"작고한 정치인 카드를 넣는 팩입니다." },
  { id:"pack_legend", name:"레전드 정치인 카드팩", cardIds:[], price:300, description:"희귀도 높은 상징적 정치인 카드를 넣는 팩입니다." },
  { id:"pack_independent", name:"비주류 정치인 카드팩", cardIds:[], price:120, description:"무소속·제3지대·비주류 정치인 카드를 넣는 팩입니다." },
  { id:"pack_youth", name:"청년 정치인 카드팩", cardIds:[], price:100, description:"청년 정치인과 신진 정치인 카드를 넣는 팩입니다." },
];

const achievements = [
  { id:"first_play", category:"전투", title:"첫 출전", description:"대전을 1회 완료", metric:"plays", target:1, reward:25 },
  { id:"play_5", category:"전투", title:"판이 커진다", description:"대전을 10회 완료", metric:"plays", target:10, reward:60 },
  { id:"play_10", category:"전투", title:"정치 고인물 입문", description:"대전을 30회 완료", metric:"plays", target:30, reward:150 },
  { id:"play_25", category:"전투", title:"선거판의 단골", description:"대전을 75회 완료", metric:"plays", target:75, reward:300 },
  { id:"first_win", category:"전투", title:"첫 승리", description:"대전에서 1회 승리", metric:"wins", target:1, reward:50 },
  { id:"win_3", category:"전투", title:"연승의 냄새", description:"대전에서 5회 승리", metric:"wins", target:5, reward:100 },
  { id:"win_10", category:"전투", title:"선거의 제왕", description:"대전에서 20회 승리", metric:"wins", target:20, reward:250 },
  { id:"win_25", category:"전투", title:"정치몬 챔피언", description:"대전에서 50회 승리", metric:"wins", target:50, reward:500 },
  { id:"ai_play_3", category:"AI 대전", title:"AI 분석관", description:"AI 대전을 5회 완료", metric:"aiPlays", target:5, reward:50 },
  { id:"ai_win_5", category:"AI 대전", title:"알고리즘 킬러", description:"AI 대전에서 10회 승리", metric:"aiWins", target:10, reward:150 },
  { id:"ai_win_15", category:"AI 대전", title:"싱글 플레이 마스터", description:"AI 대전에서 30회 승리", metric:"aiWins", target:30, reward:350 },
  { id:"pvp_play_1", category:"PvP", title:"실전 데뷔", description:"PvP 대전을 3회 완료", metric:"pvpPlays", target:3, reward:60 },
  { id:"pvp_win_1", category:"PvP", title:"첫 실전 승리", description:"PvP 대전에서 3회 승리", metric:"pvpWins", target:3, reward:120 },
  { id:"pvp_win_5", category:"PvP", title:"랭커의 기질", description:"PvP 대전에서 10회 승리", metric:"pvpWins", target:10, reward:250 },
  { id:"pvp_win_15", category:"PvP", title:"결투의 전설", description:"PvP 대전에서 25회 승리", metric:"pvpWins", target:25, reward:500 },
  { id:"open_1", category:"수집", title:"팩 맛보기", description:"카드팩 1회 개봉", metric:"packsOpened", target:1, reward:15 },
  { id:"open_5", category:"수집", title:"팩을 찢는 손", description:"카드팩 10회 개봉", metric:"packsOpened", target:10, reward:50 },
  { id:"open_15", category:"수집", title:"개봉 전문가", description:"카드팩 30회 개봉", metric:"packsOpened", target:30, reward:130 },
  { id:"pull_50", category:"수집", title:"카드 더미", description:"카드를 150장 획득", metric:"cardsPulled", target:150, reward:100 },
  { id:"collect_15", category:"수집", title:"수집가", description:"카드 25종 보유", metric:"ownedCards", target:25, reward:70 },
  { id:"collect_30", category:"수집", title:"도감의 주인", description:"카드 50종 보유", metric:"ownedCards", target:50, reward:180 },
  { id:"collect_50", category:"수집", title:"정치몬 박물관", description:"카드 75종 보유", metric:"ownedCards", target:75, reward:350 },
  { id:"ssr_3", category:"수집", title:"SSR의 기운", description:"SSR 카드 3종 보유", metric:"ownedSSR", target:3, reward:150 },
  { id:"ssr_6", category:"수집", title:"전설의 내각", description:"SSR 카드 6종 보유", metric:"ownedSSR", target:6, reward:300 },
  { id:"tutorial_complete", category:"학습", title:"첫 의정 수업", description:"튜토리얼을 완료", metric:"tutorial", target:1, reward:25 },
];

// 전과 판정은 각 인물 카드의 tags에 "criminal_record"를 직접 붙여 관리합니다.
// 죽은 정치인 팩은 아래 pack_legacy 카드 풀에 직접 추가합니다.
const criminalRecordCardIds = new Set(["character_54","character_55","character_57","character_64","character_70","character_71","character_72","character_73"]);
const femaleCardIds = new Set(["character_04","character_45","character_48","character_51","character_53","character_57","character_59","character_71"]);
const packAssignments = {
  pack_president: [
    ...Array.from({length:17}, (_,i)=>`character_${String(i+1).padStart(2,"0")}`),
    ...Array.from({length:6}, (_,i)=>`strategy_${String(i+1).padStart(2,"0")}`),
    "character_34","character_35","character_36","character_41","character_72","character_73","strategy_11","strategy_14","strategy_15","strategy_17","strategy_19","strategy_21","strategy_24","strategy_25","strategy_26","strategy_27","strategy_28","strategy_29",
  ],
  pack_people_power: [
    "character_02","character_04","character_05","character_08","character_12","character_14",
    ...Array.from({length:7}, (_,i)=>`character_${String(i+18).padStart(2,"0")}`),
    "character_30","character_53","character_54","character_58","character_59","character_61","character_63","character_65","strategy_07","strategy_08","strategy_13","strategy_16","strategy_23","strategy_24","strategy_26","strategy_27",
  ],
  pack_democratic: [
    "character_01",
    ...Array.from({length:4}, (_,i)=>`character_${String(i+25).padStart(2,"0")}`),
    "character_33","character_34","character_36","character_37",
    ...Array.from({length:6}, (_,i)=>`character_${String(i+42).padStart(2,"0")}`),
    "character_56","character_57","character_69","character_72","character_73","strategy_09","strategy_10","strategy_12","strategy_15","strategy_19","strategy_21","strategy_24","strategy_25","strategy_27","strategy_28","strategy_29","strategy_30",
  ],
  pack_assembly: ["character_01","character_18","character_19","character_22","character_25","character_26","character_28","character_29","character_36","character_42","character_45","character_46","character_47","character_53","character_56","character_57","character_59","character_60","character_61","character_63","character_64","character_71","character_73","strategy_12","strategy_13","strategy_16","strategy_18","strategy_19","strategy_20","strategy_25","strategy_27"],
  pack_legacy: [
    ...Array.from({length:9}, (_,i)=>`character_${String(i+6).padStart(2,"0")}`),
    "character_17","character_33","character_39","character_67","character_68","character_69","character_70",
  ],
  pack_independent: ["character_29","character_30","character_31","character_48","character_49","character_50","character_51","character_52","character_55","character_60","character_64","character_71","strategy_18","strategy_19","strategy_22","strategy_27"],
  pack_youth: ["character_27","character_29","character_32","character_42","character_58","character_61","character_62","character_71","strategy_04","strategy_18","strategy_24","strategy_27"],
  pack_legend: [...cards.filter(card=>card.type==="character"&&RARITIES.indexOf(card.rarity)<=RARITIES.indexOf("SR")).map(card=>card.id),"character_55","character_64"],
};
cards.forEach(card => {
  const assigned = Object.entries(packAssignments).filter(([,ids])=>ids.includes(card.id)).map(([packId])=>packId);
  if(criminalRecordCardIds.has(card.id))card.tags=[...new Set([...(card.tags||[]),"criminal_record"])];
  if(card.type==="character"){
    const tags=new Set(card.tags||[]);
    tags.delete("female");tags.delete("male");
    tags.add(femaleCardIds.has(card.id)?"female":"male");
    card.tags=[...tags];
  }
  card.packIds = [...new Set([...(card.packIds||[]), ...(card.packId?[card.packId]:[]), ...assigned])];
});
settings.tokenTypes = settings.types.map(type => type.id);
settings.tokenLabels = Object.fromEntries(settings.types.map(type => [type.id, type.label]));
settings.tokenColors = Object.fromEntries(settings.types.map(type => [type.id, type.color]));
settings.attributeLabels = settings.tokenLabels;
const cardById = Object.fromEntries(cards.map(card => [card.id, card]));
const cardStage = card => card?.stage || (card?.type==="character"&&card.rarity==="HR" ? "vmax" : card?.type==="character"&&card.rarity==="SSR" ? "v" : null);
const isVCard = card => cardStage(card)==="v";
const isVmaxCard = card => cardStage(card)==="vmax";
